#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KazanGuide.Resource", IsApplication=true)]

namespace KazanGuide
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int p1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int p2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int p3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int p4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int p5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int p6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int p7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int p8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int p9 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int imageView1 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int listView1 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int relativeLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int textView2 = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SightSeeingListItem = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
